export const CHANGE_LANGUAGE = 'CHANGE LANGUAGE';
export const SET_ACTIVE_USER = 'SET_ACTIVE_USER';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const SET_CARD_STATUS = 'SET_CARD_STATUS';
//categories
export const POST_CATEGORY = 'POST_CATEGORY';
export const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES';
export const GET_SINGLE_CATEGORY = 'FETCH_SINGLE_CATEGORY'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY;';
//items
export const POST_ITEMS = 'POST_CATEGORY';
export const FETCH_ALL_ITEM = 'FETCH_ALL_CATEGORIES';
export const GET_SINGLE_ITEM= 'FETCH_SINGLE_CATEGORY'
export const UPDATE_ITEM= 'UPDATE_CATEGORY';
export const DELETE_ITEM = 'DELETE_CATEGORY;';